name: Custom Windows Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Build RustDesk Windows
        run: flutter build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-windows
          path: build/windows/runner/Release
