name: RustDesk Windows Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Enable desktop support
        run: flutter config --enable-windows-desktop

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install build dependencies (CMake, Ninja, etc.)
        run: |
          choco install -y cmake
          choco install -y ninja
          choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

      - name: Build RustDesk for Windows
        run: flutter build windows

      - name: Upload Windows EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: build/windows/runner/Release
